#!/usr/bin/env python3

# Generate a Make fragment to describe package's dependencies.
# This alows Make to build the dependency graph for a package.
#
# Variables (PKG_NAME, PKG_VER, PKG_DEPS) are passed as arguments already
# already expanded by Make.

from __future__ import annotations

import argparse
import pathlib
import re


RESET_VARS = (
    "PKG_NAME",
    "PKG_VER",
    "PKG_DEPS",
    "PKG_WORK_DIR",
    "PKG_SOURCE_STAMP",
    "PKG_PATCH_STAMP",
    "PKG_BUILD_STAMP",
    "PKG_INSTALL_STAMP",
)


def sanitise(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]+", "_", name)


def render(
    *,
    pkg_name: str,
    pkg_version: str,
    deps: list[str],
    pkg_dir: pathlib.Path,
    pkg_env: pathlib.Path,
) -> str:
    pkg_id = sanitise(pkg_name)
    dep_ids = [(dep, sanitise(dep)) for dep in deps]

    guard = f"_PKG_LOADED_{pkg_id}"

    lines: list[str] = []
    lines.append("# Autogenerated")
    lines.append(f"ifndef {guard}")
    lines.append(f"{guard} := 1")
    lines.append("")
    lines.append(f"PKG_NAME := {pkg_name}")
    lines.append(f"PKG_VER := {pkg_version}")
    if deps:
        lines.append(f"PKG_DEPS := {' '.join(deps)}")
    lines.append(f"include {pkg_env}")
    lines.append("")

    lines.append(f"PKG_DIR_{pkg_id} := {pkg_dir}")
    lines.append(f"PKG_STAMP_{pkg_id} := $(PKG_INSTALL_STAMP)")
    lines.append(f"PKG_SRC_STAMP_{pkg_id} := $(PKG_SOURCE_STAMP)")
    lines.append(f"PKG_VER_{pkg_id} := $(PKG_VER)")
    lines.append(f"PKG_DEPS_{pkg_id} := {' '.join(deps) if deps else ''}")
    lines.append("")

    if deps:
        for dep in deps:
            lines.append(f"-include $(DEP_DIR)/{dep}.deps.mk")
        lines.append("")

    lines.append(f"ALL_PACKAGE_STAMPS += $(PKG_STAMP_{pkg_id})")
    lines.append("")

    lines.append(f".PHONY: {pkg_name}")
    lines.append(f"{pkg_name}: $(PKG_STAMP_{pkg_id})")
    lines.append("")

    # Source preparation (fetch/extract/patch) runs without waiting for deps
    lines.append(f"$(PKG_SRC_STAMP_{pkg_id}):")
    lines.append(f"\t@$(MAKE) -C $(PKG_DIR_{pkg_id}) --no-print-directory source")
    lines.append("")

    # Build/install waits for both source prep and dependency install stamps
    if deps:
        prereqs = " ".join(f"$(PKG_STAMP_{d_id})" for _, d_id in dep_ids)
        lines.append(f"$(PKG_STAMP_{pkg_id}): $(PKG_SRC_STAMP_{pkg_id}) {prereqs}")
    else:
        lines.append(f"$(PKG_STAMP_{pkg_id}): $(PKG_SRC_STAMP_{pkg_id})")
    lines.append(f"\t@echo \"==> Build {pkg_name} {pkg_version}\"")
    lines.append(f"\t@$(MAKE) -C $(PKG_DIR_{pkg_id}) --no-print-directory")
    lines.append("")

    for var in RESET_VARS:
        lines.append(f"undefine {var}")
    lines.append("")
    lines.append(f"endif  # {guard}")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a package depfile")
    parser.add_argument("--name", required=True)
    parser.add_argument("--ver", required=True)
    parser.add_argument("--deps", default="")
    parser.add_argument("--pkg-dir", required=True, type=pathlib.Path)
    parser.add_argument("--pkg-env", required=True, type=pathlib.Path)
    parser.add_argument("--out", required=True, type=pathlib.Path)
    args = parser.parse_args()

    deps = args.deps.split()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    content = render(
        pkg_name=args.name,
        pkg_version=args.ver,
        deps=deps,
        pkg_dir=args.pkg_dir.resolve(),
        pkg_env=args.pkg_env.resolve(),
    )
    args.out.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
