PKG_NAME := util-linux
PKG_VER := 2.41.3
PKG_BUILD_SCHEME := autotools
PKG_CONFIGURE_OPTS := \
   --disable-all-programs \
   --disable-nls \
   --enable-libuuid \
   --disable-static \
   --disable-dependency-tracking \
   --without-python \
   --without-systemd \
   --without-tinfo \
   --without-ncurses \
   --without-readline \
   --without-cap-ng \
   --without-audit
include ../shared/pkg.mk
