add_dracutmodules+=" crypt dm "
omit_dracutmodules+=" network nfs cifs mdraid dmraid "
force_drivers+=" dm-mod dm-crypt af_alg algif_skcipher libaes aes_generic aes-arm64 libpoly1305 nhpoly1305 adiantum libchacha chacha-neon chacha_generic "
install_items+=" /etc/crypttab /usr/bin/cryptsetup-passphrase-agent "

# Defaults
kernel_cmdline="
 rd.shell=0                  # Disable emergency shell
 rd.emergency=reboot         # Reboot on critical boot error
 panic=5                     # Reboot time after kernel panic
 rd.retry=30                 # Give up on disk discovery after this time
 rd.luks.options=timeout=10" # Passphrase backend timeout
