PKG_NAME := libconfuse
PKG_VER := 3.3
PKG_BUILD_SCHEME := autotools
PKG_CONFIGURE_OPTS := \
   --disable-examples \
   --disable-static   \
   --disable-nls      \
   --disable-dependency-tracking
include ../shared/pkg.mk
