#!/bin/bash

set -eu

[[ ${IGconf_device_storage_type} == emmc ]] || exit 0
igconf isy image_ptable_protect || exit 0

chroot $1 apt install -y mmc-utils

do_install() {
   [ -d "$1" ] || return 0
   [ -d "$2" ] || return 0
   rsync -av "$1/" "$2/"
  }

do_install ../device/emmc/initramfs-tools "$1/etc/initramfs-tools"
do_install ../device/emmc/dracut.conf.d "$1/etc/dracut.conf.d"
do_install ../device/emmc/dracut.modules.d "$1/usr/lib/dracut/modules.d"
